import * as fs from 'fs';
import * as path from 'path';
import { WorkflowGraph } from './types';

interface GenerateOptions {
  workflow: WorkflowGraph;
  config: Record<string, string>;
  customEnvVars?: string;
  workspaceRoot?: string;
}

export interface GeneratedFiles {
  pythonFile: string;
  envFile: string;
  readmeFile: string;
  dirStructure: string[];
  dirPath: string;
}

export class PythonGenerator {
  static async generate(options: GenerateOptions): Promise<GeneratedFiles> {
    const { workflow, config, customEnvVars, workspaceRoot } = options;

    const safeSlug = workflow.description
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .slice(0, 40);

    const timestamp = new Date().toISOString().split('T')[0];
    const dirName = `workflow_${safeSlug}_${timestamp}`;
    const baseDir = workspaceRoot ? path.join(workspaceRoot, 'workflows', dirName) : null;

    const workflowSteps = workflow.steps || [];
    const stepFiles: string[] = [];

    // Generate individual step .py files
    for (let i = 0; i < workflowSteps.length; i++) {
      const step = workflowSteps[i];
      const stepFileName = `step_${i + 1}_${step.toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 20)}.py`;
      const stepContent = `#!/usr/bin/env python3
"""
Step ${i + 1}: ${step}
Part of: ${workflow.description}
Generated by VibeFlow
"""

def execute_step_${i + 1}():
    """
    Execute step ${i + 1}: ${step}
    """
    print("[STEP ${i + 1}] ${step}")
    # TODO: Implement your logic here
    # This is a placeholder - the AI will generate actual code
    pass

if __name__ == "__main__":
    execute_step_${i + 1}()
`;
      stepFiles.push(stepFileName);
      if (baseDir) {
        fs.writeFileSync(path.join(baseDir, stepFileName), stepContent, 'utf8');
      }
    }

    // Generate main agent.py that imports all steps
    const pythonContent = `#!/usr/bin/env python3
"""
VibeFlow Generated Workflow: ${workflow.description}
Generated: ${new Date().toISOString()}
Author: VibeFlow Extension by Virgil Junior Adoleyine

== SETUP ==
1. pip install -r requirements.txt
2. Copy .env.local to .env and fill in any additional keys
3. python agent.py

== CLOUD ==
Get full visual UI, history, and 400+ integrations at: https://vibeflow-cloud.vercel.app
"""

import os
import sys
from dotenv import load_dotenv

load_dotenv('.env')

# OpenRouter client
import httpx

OPENROUTER_KEY = os.environ.get('VIBEFLOW_OPENROUTER_KEY', '')
E2B_API_KEY = os.environ.get('VIBEFLOW_E2B_API_KEY', '')
COMPOSIO_API_KEY = os.environ.get('VIBEFLOW_COMPOSIO_API_KEY', '')
INNGEST_SIGNING_KEY = os.environ.get('VIBEFLOW_INNGEST_SIGNING_KEY', '')
INNGEST_EVENT_KEY = os.environ.get('VIBEFLOW_INNGEST_EVENT_KEY', '')
NEON_DATABASE_URL = os.environ.get('VIBEFLOW_NEON_DATABASE_URL', '')
UPSTASH_REDIS_URL = os.environ.get('VIBEFLOW_UPSTASH_REDIS_URL', '')
UPSTASH_REDIS_TOKEN = os.environ.get('VIBEFLOW_UPSTASH_REDIS_TOKEN', '')

def call_openrouter(messages: list, model: str = 'anthropic/claude-sonnet-4-5') -> str:
    """Call OpenRouter API and return the response text."""
    if not OPENROUTER_KEY:
        raise ValueError("OpenRouter API key not set. Set VIBEFLOW_OPENROUTER_KEY in .env")
    
    response = httpx.post(
        'https://openrouter.ai/api/v1/chat/completions',
        headers={
            'Authorization': f'Bearer {OPENROUTER_KEY}',
            'Content-Type': 'application/json',
            'HTTP-Referer': 'https://vibeflow-cloud.vercel.app',
            'X-Title': 'VibeFlow Agent'
        },
        json={
            'model': model,
            'messages': messages,
            'max_tokens': 2000
        },
        timeout=60.0
    )
    response.raise_for_status()
    return response.json()['choices'][0]['message']['content']

def planner(task: str) -> list:
    """PLANNER: Break task into ordered steps."""
    print(f'[PLANNER] Breaking down: {task}')
    response = call_openrouter([
        {'role': 'system', 'content': 'You are a workflow planner. Break the task into ordered Python steps. Return a JSON list of step descriptions.'},
        {'role': 'user', 'content': task}
    ])
    import json
    try:
        return json.loads(response.replace('\`\`\`json', '').replace('\`\`\`', '').strip())
    except:
        return [task]

def executor(step: str) -> str:
    """EXECUTOR: Write Python code for a step."""
    print(f'[EXECUTOR] Coding: {step}')
    return call_openrouter([
        {'role': 'system', 'content': 'Write Python 3 code for the given step. Return only the code.'},
        {'role': 'user', 'content': step}
    ])

def reflector(code: str, error: str, attempt: int = 1) -> str:
    """REFLECTOR: Self-heal broken code. Retries until fixed."""
    print(f'[REFLECTOR] Healing attempt {attempt}...')
    return call_openrouter([
        {'role': 'system', 'content': 'Fix the broken Python code. Return only fixed code.'},
        {'role': 'user', 'content': f'Code:\\n{code}\\n\\nError:\\n{error}'}
    ])

def formatter(results: list) -> str:
    """FORMATTER: Package results into clean output."""
    print('[FORMATTER] Formatting final result...')
    return call_openrouter([
        {'role': 'system', 'content': 'Summarize the workflow execution results in a clear, user-friendly way.'},
        {'role': 'user', 'content': f'Results: {results}'}
    ])

def run_workflow():
    """Main 4-node LangGraph-style agent loop."""
    task = """${workflow.description}"""
    print(f'\\n⚡ VibeFlow Agent Starting: {task}\\n')

    # Node 1: Plan
    steps = planner(task)
    print(f'Plan: {steps}\\n')

    # Node 2 + 3: Execute + Reflect
    results = []
    for step in steps:
        code = executor(step)
        attempt = 0
        while attempt < 10:  # self-heal until success
            try:
                exec_globals = {}
                exec(code, exec_globals)
                results.append({'step': step, 'status': 'success'})
                break
            except Exception as e:
                attempt += 1
                code = reflector(code, str(e), attempt)
                if attempt >= 10:
                    results.append({'step': step, 'status': 'failed', 'error': str(e)})

    # Node 4: Format
    final = formatter(results)
    print(f'\\n✅ Result:\\n{final}')
    return final

if __name__ == '__main__':
    run_workflow()
`;

    // Generate .env.local with actual values from settings
    let envLines = `# VibeFlow Generated Environment Variables
# Copy this file to .env and add any additional keys needed.
# DO NOT commit .env to version control.

`;
    
    // Add all config values (mask sensitive ones for display)
    for (const [key, value] of Object.entries(config)) {
      if (value && value.trim() !== '') {
        envLines += `VIBEFLOW_${key.toUpperCase()}=${value}\n`;
      }
    }
    
    // Add custom env vars from user
    if (customEnvVars) {
      envLines += `\n# Custom environment variables (add yours here)\n`;
      const customVars = customEnvVars.split(',').map(v => v.trim()).filter(v => v);
      for (const v of customVars) {
        envLines += `# VIBEFLOW_${v.toUpperCase()}=your_value_here\n`;
      }
    }
    
    envLines += `\n# If the AI generated code needs additional API keys,\n`;
    envLines += `# add them here with VIBEFLOW_ prefix\n`;
    
    const envContent = envLines;

    // Generate README.md
    const readmeContent = `# VibeFlow Workflow: ${workflow.description}

> Generated by [VibeFlow VS Code Extension](https://marketplace.visualstudio.com/items?itemName=VirgilAdoleyine.vibeflow)
> Cloud UI available at: **[vibeflow-cloud.vercel.app](https://vibeflow-cloud.vercel.app)**

## What This Does

${workflow.description}

## Directory Structure

\`\`\`
workflows/${dirName}/
├── agent.py           # Main workflow runner
${stepFiles.map(f => `├── ${f}`).join('\n')}
├── .env.local         # Environment variables (copy to .env)
├── requirements.txt   # Python dependencies
└── README.md          # This file
\`\`\`

## Setup

\`\`\`bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Configure environment
cp .env.local .env
# Edit .env with your actual API keys

# 3. Run the workflow
python agent.py
\`\`\`

## Steps

${workflowSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

## How It Works

This workflow uses a **4-node AI agent graph**:

| Node | Role |
|------|------|
| **Planner** | Breaks your task into ordered steps using Claude |
| **Executor** | Writes Python code per step via OpenRouter |
| **Reflector** | Self-heals errors — retries until the code works |
| **Formatter** | Packages the result into a clear human-readable response |

## Want the Full Experience?

Visit **[vibeflow-cloud.vercel.app](https://vibeflow-cloud.vercel.app)** for:
- 🎨 Visual node canvas to build and edit workflows
- 📊 Execution history and live streaming logs
- 🔗 400+ OAuth integrations (Gmail, Slack, GitHub, Notion...)
- 🧠 Memory of past workflows
- 🛡️ Built-in compliance checker

## Contribute

### Cloud + Community Repos (sync both at once)

\`\`\`bash
# Pull from both repos
git pull origin main && git pull community main

# Push to both repos
git push origin main && git push community main

# Or do both at once
git pull origin main && git pull community main && git push origin main && git push community main
\`\`\`

### Community Repo
Developers can self-host and contribute to VibeFlow at the community repo.

---

## RegGuard — Compliance for Developers

This workflow was compliance-checked using **[RegGuard](https://github.com/VirgilAdoleyine/regguard)** —
a VS Code extension that helps devs ship faster without breaking regulations.

- 🔗 **GitHub**: [github.com/VirgilAdoleyine/regguard](https://github.com/VirgilAdoleyine/regguard)
- 🔍 **VS Code Marketplace**: Search **"RegGuard"**
- 📦 **Open VSX**: Search **"RegGuard"**

⭐ Please star RegGuard to help the project grow and support compliance tooling for developers worldwide.

---

*Built by Virgil Junior Adoleyine — 17-year-old developer from Ghana 🇬🇭*
`;

    // Generate requirements.txt
    const requirementsContent = `# VibeFlow Workflow Dependencies
httpx
python-dotenv
`;

    // Write files to disk if workspaceRoot provided
    if (baseDir) {
      fs.mkdirSync(baseDir, { recursive: true });
      fs.writeFileSync(path.join(baseDir, 'agent.py'), pythonContent, 'utf8');
      fs.writeFileSync(path.join(baseDir, '.env.local'), envContent, 'utf8');
      fs.writeFileSync(path.join(baseDir, '.env.vibeflow'), envContent, 'utf8');
      fs.writeFileSync(path.join(baseDir, 'README.md'), readmeContent, 'utf8');
      fs.writeFileSync(path.join(baseDir, 'requirements.txt'), requirementsContent, 'utf8');
      for (let i = 0; i < stepFiles.length; i++) {
        const stepContent = `#!/usr/bin/env python3
"""
Step ${i + 1}: ${workflowSteps[i]}
Part of: ${workflow.description}
Generated by VibeFlow
"""

def execute_step_${i + 1}():
    """
    Execute step ${i + 1}: ${workflowSteps[i]}
    """
    print("[STEP ${i + 1}] ${workflowSteps[i]}")
    # TODO: Implement your logic here
    pass

if __name__ == "__main__":
    execute_step_${i + 1}()
`;
        fs.writeFileSync(path.join(baseDir, stepFiles[i]), stepContent, 'utf8');
      }
    }

    return {
      pythonFile: pythonContent,
      envFile: envContent,
      readmeFile: readmeContent,
      dirStructure: [
        `workflows/${dirName}/`,
        `workflows/${dirName}/agent.py`,
        ...stepFiles.map(f => `workflows/${dirName}/${f}`),
        `workflows/${dirName}/.env.local`,
        `workflows/${dirName}/requirements.txt`,
        `workflows/${dirName}/README.md`
      ],
      dirPath: baseDir || `workflows/${dirName}`
    };
  }
}
